"""null addition date for listinghistory

Revision ID: 0badc839e116
Revises: 5b9dfb4891d2
Create Date: 2025-11-19 13:00:34.526022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0badc839e116'
down_revision: Union[str, Sequence[str], None] = '5b9dfb4891d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('listings_analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites', sa.Integer(), nullable=False))
        batch_op.drop_column('favorties')

    with op.batch_alter_table('listings_history', schema=None) as batch_op:
        batch_op.alter_column('addition_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('listings_parser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('listings_parser', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('currency')

    with op.batch_alter_table('listings_history', schema=None) as batch_op:
        batch_op.alter_column('addition_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('listings_analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorties', sa.INTEGER(), nullable=False))
        batch_op.drop_column('favorites')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
