"""add dimension field

Revision ID: 2688ee5b0882
Revises: 4a0b98c2b69e
Create Date: 2025-11-25 12:05:59.522536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from server.schemas.container import ContainerDimension


# revision identifiers, used by Alembic.
revision: str = '2688ee5b0882'
down_revision: Union[str, Sequence[str], None] = '4a0b98c2b69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dimension', sa.String(length=64), nullable=False, server_default=ContainerDimension.UNKNOWN.value))

    with op.batch_alter_table('listings_parser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dimension', sa.String(length=64), nullable=False, server_default=ContainerDimension.UNKNOWN.value))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings_parser', schema=None) as batch_op:
        batch_op.drop_column('dimension')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('dimension')

    # ### end Alembic commands ###
