"""add url reference to user photo

Revision ID: 4a0b98c2b69e
Revises: bd9a9e679ddf
Create Date: 2025-11-23 21:16:41.685556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0b98c2b69e'
down_revision: Union[str, Sequence[str], None] = 'bd9a9e679ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_url', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.drop_column('ref_url')

    # ### end Alembic commands ###
