"""add parser id to listings

Revision ID: bd9a9e679ddf
Revises: 0badc839e116
Create Date: 2025-11-19 13:50:20.193522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9a9e679ddf'
down_revision: Union[str, Sequence[str], None] = '0badc839e116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parser_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_listing_parser_id', 'listings_parser', ['parser_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_listing_parser_id', type_='foreignkey')
        batch_op.drop_column('parser_id')

    # ### end Alembic commands ###
